data = 1234
print("原本的資料型態:", type(data))
print("原本的data", data)
print("-" * 20)
data = str(data)
print("轉換後的資料型態:", type(data))
print("轉換後的data", data)
print("-" * 20)
data = float(data)
print("轉換後的資料型態:", type(data))
print("轉換後的data", data)
print("-" * 20)
data = 12.34
print("原本的資料型態:", type(data))
print("原本的data", data)
print("-" * 20)
data = int(data)
print("轉換後的資料型態:", type(data))
print("轉換後的data", data)