print("1.\t", "HELLO\nPython\ngood")
print("--------------")
print("2.\t", "HELLO\tPython\tgood")
print("--------------")
print("3.\t", "HELLO\rPython\rgood")
print("--------------")
print("4.\t", "HELLO\bPython\bgood")
print("--------------")
print("5.\t", "HELLO\'Python\'good")
print("--------------")
print("6.\t", "HELLO\"Python\"good")
print("--------------")
print("7.\t", "HELLO\\Python\\good")