import datetime as dt

print("1.\t", dt.datetime(2021, 10, 10, 12, 27, 30))
print("1.\t", dt.datetime(2021, 10, 10))

date_time = dt.datetime.now()
print("1.\t現在日期與時間:", date_time)
print("2.\t現在時間戳:", date_time.timestamp())
print("3.\t現在日期:", date_time.date())
print("4.\t現在星期:", date_time.weekday())
print("5.\t現在時間:", date_time.time())
print("-" * 30)
print("6.\t年:", date_time.year)
print("7.\t月:", date_time.month)
print("8.\t日:", date_time.day)
print("9.\t時:", date_time.hour)
print("10.\t分:", date_time.minute)
print("11.\t秒:", date_time.second)
print("12.\t微秒:", date_time.microsecond)
print("13.\t時區:", date_time.tzinfo)
print("-" * 30)
print("14.\t本地時間含時區:", date_time.astimezone())
print("15.\t本地時間含時區:", date_time.astimezone().tzinfo)
date_time_utc = dt.datetime.now(dt.timezone.utc)
print("16.\tUTC時間含時區:", date_time_utc)
print("17.\tUTC時間含時區:", date_time_utc.tzinfo)

print("1.\t", dt.timedelta(days=7))
date_time = dt.datetime.now()
print("2.\t", date_time)
date_time_a = date_time + dt.timedelta(days=7)
print("3.\t", date_time_a)
date_time_b = date_time + dt.timedelta(days=30)
print("4.\t", date_time_b)
date_time_c = date_time + dt.timedelta(days=-6)
print("5.\t", date_time_c)

date_time = dt.datetime.now()
print("1.\t現在日期與時間:", date_time)

date_now_stamp = date_time.timestamp()
print("2.\t現在日期與時間轉成時間戳:", date_now_stamp)

date_co = dt.datetime.fromtimestamp(date_now_stamp)
print("3.\t時間戳轉成現在日期與時間:", date_co)
